_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: outputs/train/moirai_small/lotsa_v1_unweighted/iqn_data_filter_ratio0.02_iqn1.5/checkpoints/last.ckpt
  # _target_: huggingface_hub.hf_hub_download
  # repo_id: Salesforce/moirai-1.0-R-small
  # filename: model.ckpt
num_samples: 100
patch_size: ???
context_length: ???